demo.constant('dictionary',{
  name:[
    {value:'1',text:'wade'},
    {value:'2',text:'bosh'},
    {value:'3',text:'james'},
    {value:'4',text:'kobe'},
    ]
});
demo.value('test',{
 test1:'test111',
  test2:'test222'
})